# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'intruder_alert.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ctypes
import threading

def lock_pc():
    ctypes.windll.user32.LockWorkStation()


class IntruderAlertDialog(QtWidgets.QDialog):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.ui = Ui_dialog()
        self.ui.setupUi(self)
        threading.Timer(3, lock_pc).start()

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(400, 150)
        dialog.setStyleSheet("background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgba(252, 184, 184, 255), stop: 1 rgba(178, 214, 240, 255));")
        self.gridLayout_2 = QtWidgets.QGridLayout(dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grid_layout = QtWidgets.QGridLayout()
        self.grid_layout.setSpacing(0)
        self.grid_layout.setObjectName("grid_layout")
        self.text_widget = QtWidgets.QWidget(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_widget.sizePolicy().hasHeightForWidth())
        self.text_widget.setSizePolicy(sizePolicy)
        self.text_widget.setStyleSheet("background: none")
        self.text_widget.setObjectName("text_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.text_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.alert_title_label = QtWidgets.QLabel(self.text_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alert_title_label.sizePolicy().hasHeightForWidth())
        self.alert_title_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.alert_title_label.setFont(font)
        self.alert_title_label.setObjectName("alert_title_label")
        self.verticalLayout.addWidget(self.alert_title_label)
        self.grid_layout.addWidget(self.text_widget, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.alert_icon = QtWidgets.QLabel(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alert_icon.sizePolicy().hasHeightForWidth())
        self.alert_icon.setSizePolicy(sizePolicy)
        self.alert_icon.setStyleSheet("background: none")
        self.alert_icon.setText("")
        self.alert_icon.setPixmap(QtGui.QPixmap(":/images/alert_icon.png"))
        self.alert_icon.setObjectName("alert_icon")
        self.grid_layout.addWidget(self.alert_icon, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.grid_layout, 0, 0, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Alert"))
        self.alert_title_label.setText(_translate("dialog", "Alert! An intruder was detected!!!"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
