# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_widget_last.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator


class RegisterWidget(QWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.ui = Ui_Form()
        self.ui.setupUi(self)


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 576)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.centralwidget_hlayout = QtWidgets.QHBoxLayout()
        self.centralwidget_hlayout.setSpacing(0)
        self.centralwidget_hlayout.setObjectName("centralwidget_hlayout")
        self.left_frame = QtWidgets.QFrame(Form)
        self.left_frame.setMinimumSize(QtCore.QSize(511, 0))
        self.left_frame.setAutoFillBackground(False)
        self.left_frame.setStyleSheet("background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgba(14, 201, 242, 107), stop: 1 rgba(34, 173, 204, 255));")
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.left_frame_vlayout = QtWidgets.QVBoxLayout()
        self.left_frame_vlayout.setObjectName("left_frame_vlayout")
        self.logo = QtWidgets.QLabel(self.left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMaximumSize(QtCore.QSize(290, 90))
        self.logo.setStyleSheet("background: none")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/images/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.left_frame_vlayout.addWidget(self.logo)
        self.ellipse = QtWidgets.QFrame(self.left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ellipse.sizePolicy().hasHeightForWidth())
        self.ellipse.setSizePolicy(sizePolicy)
        self.ellipse.setMinimumSize(QtCore.QSize(350, 350))
        self.ellipse.setMaximumSize(QtCore.QSize(350, 350))
        self.ellipse.setStyleSheet("border-radius: 175")
        self.ellipse.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ellipse.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ellipse.setObjectName("ellipse")
        self.ellipse_icon = QtWidgets.QLabel(self.ellipse)
        self.ellipse_icon.setGeometry(QtCore.QRect(70, 60, 201, 241))
        self.ellipse_icon.setStyleSheet("background: none\n"
"\n"
"")
        self.ellipse_icon.setText("")
        self.ellipse_icon.setPixmap(QtGui.QPixmap(":/images/phone.png"))
        self.ellipse_icon.setScaledContents(True)
        self.ellipse_icon.setObjectName("ellipse_icon")
        self.left_frame_vlayout.addWidget(self.ellipse, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.left_frame_vlayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.left_frame_vlayout)
        self.centralwidget_hlayout.addWidget(self.left_frame)
        self.right_frame = QtWidgets.QFrame(Form)
        self.right_frame.setMinimumSize(QtCore.QSize(511, 0))
        self.right_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.right_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grid_layout = QtWidgets.QGridLayout()
        self.grid_layout.setHorizontalSpacing(12)
        self.grid_layout.setObjectName("grid_layout")
        self.phone_number_label = QtWidgets.QLabel(self.right_frame)
        self.phone_number_label.setStyleSheet("margin: 10px 0;\n"
"font-weight: bold;")
        self.phone_number_label.setObjectName("phone_number_label")
        self.grid_layout.addWidget(self.phone_number_label, 5, 4, 1, 4)
        self.female_radiobtn = QtWidgets.QRadioButton(self.right_frame)
        self.female_radiobtn.setObjectName("female_radiobtn")
        self.grid_layout.addWidget(self.female_radiobtn, 11, 4, 1, 2)
        self.email_le = QtWidgets.QLineEdit(self.right_frame)

        reg_ex = QRegExp(r"^\S+@\S+\.\S+$")
        email_validator = QRegExpValidator(reg_ex, self.email_le)
        self.email_le.setValidator(email_validator)
        
        self.email_le.setMinimumSize(QtCore.QSize(0, 35))
        self.email_le.setStyleSheet("borde-color: none;\n"
"background-color: rgb(149, 231, 249, 38);\n"
"border-radius: 15px;\n"
"padding: 0 8px;")
        self.email_le.setObjectName("email_le")
        self.grid_layout.addWidget(self.email_le, 6, 0, 1, 4)
        self.country_le = QtWidgets.QLineEdit(self.right_frame)
        self.country_le.setMinimumSize(QtCore.QSize(0, 35))
        self.country_le.setStyleSheet("borde-color: none;\n"
"background-color: rgb(149, 231, 249, 38);\n"
"border-radius: 15px;\n"
"padding: 0 8px;")
        self.country_le.setObjectName("country_le")
        self.grid_layout.addWidget(self.country_le, 8, 0, 1, 4)
        self.password_le = QtWidgets.QLineEdit(self.right_frame)
        self.password_le.setMinimumSize(QtCore.QSize(0, 35))
        self.password_le.setStyleSheet("borde-color: none;\n"
"background-color: rgb(149, 231, 249, 38);\n"
"border-radius: 15px;\n"
"padding: 0 8px;")
        self.password_le.setObjectName("password_le")
        self.password_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.grid_layout.addWidget(self.password_le, 10, 0, 1, 4)
        self.checkBox = QtWidgets.QCheckBox(self.right_frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("margin: 15px 0;\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.grid_layout.addWidget(self.checkBox, 12, 0, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_layout.addItem(spacerItem1, 14, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_layout.addItem(spacerItem2, 0, 0, 1, 1)
        self.login_question_label = QtWidgets.QLabel(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_question_label.sizePolicy().hasHeightForWidth())
        self.login_question_label.setSizePolicy(sizePolicy)
        self.login_question_label.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.login_question_label.setFont(font)
        self.login_question_label.setObjectName("login_question_label")
        self.grid_layout.addWidget(self.login_question_label, 13, 2, 1, 3)
        self.cpassword_label = QtWidgets.QLabel(self.right_frame)
        self.cpassword_label.setStyleSheet("margin: 10px 0;\n"
"font-weight: bold;")
        self.cpassword_label.setObjectName("cpassword_label")
        self.grid_layout.addWidget(self.cpassword_label, 9, 4, 1, 4)
        self.male_radiobtn = QtWidgets.QRadioButton(self.right_frame)
        self.male_radiobtn.setStyleSheet("")
        self.male_radiobtn.setObjectName("male_radiobtn")
        self.grid_layout.addWidget(self.male_radiobtn, 11, 2, 1, 2)
        self.sign_up_btn = QtWidgets.QPushButton(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sign_up_btn.sizePolicy().hasHeightForWidth())
        self.sign_up_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sign_up_btn.setFont(font)
        self.sign_up_btn.setStyleSheet("background-color: \"#24AFCD\";\n"
"color: white;\n"
"font-weight: bold;\n"
"border-radius: 10px;")
        self.sign_up_btn.setObjectName("sign_up_btn")
        self.grid_layout.addWidget(self.sign_up_btn, 12, 5, 1, 3)
        self.name_le = QtWidgets.QLineEdit(self.right_frame)
        reg_ex = QRegExp(r"^[a-zA-Z]{4,}(?: [a-zA-Z]+){0,2}$")
        full_name_validator = QRegExpValidator(reg_ex, self.name_le)
        self.name_le.setValidator(full_name_validator)

        self.name_le.setMinimumSize(QtCore.QSize(0, 35))
        self.name_le.setStyleSheet("borde-color: none;\n"
"background-color: rgb(149, 231, 249, 38);\n"
"border-radius: 15px;\n"
"padding: 0 8px;")
        self.name_le.setObjectName("name_le")
        self.grid_layout.addWidget(self.name_le, 3, 0, 1, 7)
        self.city_le = QtWidgets.QLineEdit(self.right_frame)
        self.city_le.setMinimumSize(QtCore.QSize(0, 35))
        self.city_le.setStyleSheet("borde-color: none;\n"
"background-color: rgb(149, 231, 249, 38);\n"
"border-radius: 15px;\n"
"padding: 0 8px;")
        self.city_le.setObjectName("city_le")
        self.grid_layout.addWidget(self.city_le, 8, 4, 1, 4)
        self.password_label = QtWidgets.QLabel(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_label.sizePolicy().hasHeightForWidth())
        self.password_label.setSizePolicy(sizePolicy)
        self.password_label.setStyleSheet("margin: 10px 0;\n"
"font-weight: bold;")
        self.password_label.setObjectName("password_label")
        self.grid_layout.addWidget(self.password_label, 9, 0, 1, 4)
        self.cpassword_le = QtWidgets.QLineEdit(self.right_frame)
        self.cpassword_le.setMinimumSize(QtCore.QSize(0, 35))
        self.cpassword_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.cpassword_le.setStyleSheet("borde-color: none;\n"
"background-color: rgb(149, 231, 249, 38);\n"
"border-radius: 15px;\n"
"padding: 0 8px;")
        self.cpassword_le.setObjectName("cpassword_le")
        self.grid_layout.addWidget(self.cpassword_le, 10, 4, 1, 4)
        self.name_label = QtWidgets.QLabel(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        self.name_label.setStyleSheet("margin: 10px 0;\n"
"font-weight: bold;")
        self.name_label.setObjectName("name_label")
        self.grid_layout.addWidget(self.name_label, 2, 0, 1, 7)
        self.city_label = QtWidgets.QLabel(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city_label.sizePolicy().hasHeightForWidth())
        self.city_label.setSizePolicy(sizePolicy)
        self.city_label.setStyleSheet("margin: 10px 0;\n"
"font-weight: bold;")
        self.city_label.setObjectName("city_label")
        self.grid_layout.addWidget(self.city_label, 7, 4, 1, 4)
        self.gener_label = QtWidgets.QLabel(self.right_frame)
        self.gener_label.setStyleSheet("margin: 10px 0;\n"
"font-weight: bold;")
        self.gener_label.setObjectName("gener_label")
        self.grid_layout.addWidget(self.gener_label, 11, 0, 1, 2)
        self.country_label = QtWidgets.QLabel(self.right_frame)
        self.country_label.setStyleSheet("margin: 10px 0;\n"
"font-weight: bold;")
        self.country_label.setObjectName("country_label")
        self.grid_layout.addWidget(self.country_label, 7, 0, 1, 4)
        self.email_label = QtWidgets.QLabel(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_label.sizePolicy().hasHeightForWidth())
        self.email_label.setSizePolicy(sizePolicy)
        self.email_label.setStyleSheet("margin: 10px 0;\n"
"font-weight: bold;")
        self.email_label.setObjectName("email_label")
        self.grid_layout.addWidget(self.email_label, 5, 0, 1, 4)
        self.phone_number_le = QtWidgets.QLineEdit(self.right_frame)
        reg_ex = QRegExp(r"^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$")
        phone_validator = QRegExpValidator(reg_ex, self.phone_number_le)
        self.phone_number_le.setValidator(phone_validator)

        self.phone_number_le.setMinimumSize(QtCore.QSize(0, 35))
        self.phone_number_le.setStyleSheet("borde-color: none;\n"
"background-color: rgb(149, 231, 249, 38);\n"
"border-radius: 15px;\n"
"padding: 0 8px;")
        self.phone_number_le.setObjectName("phone_number_le")
        self.grid_layout.addWidget(self.phone_number_le, 6, 4, 1, 4)
        self.sign_up_label = QtWidgets.QLabel(self.right_frame)
        self.sign_up_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sign_up_label.setFont(font)
        self.sign_up_label.setStyleSheet("color: \"#28B1D0\";\n"
"font-weight: bold;\n"
"margin: 10px 0 ")
        self.sign_up_label.setTextFormat(QtCore.Qt.AutoText)
        self.sign_up_label.setScaledContents(False)
        self.sign_up_label.setWordWrap(False)
        self.sign_up_label.setIndent(-3)
        self.sign_up_label.setObjectName("sign_up_label")
        self.grid_layout.addWidget(self.sign_up_label, 1, 0, 1, 2)
        self.login_btn = QtWidgets.QPushButton(self.right_frame)
        self.login_btn.setStyleSheet("font-weight: bold;\n"
"color: \"#29B2D0\";\n"
"border: none")
        self.login_btn.setObjectName("login_btn")
        self.grid_layout.addWidget(self.login_btn, 13, 5, 1, 1)
        self.gridLayout_2.addLayout(self.grid_layout, 0, 1, 1, 1)
        self.centralwidget_hlayout.addWidget(self.right_frame)
        self.horizontalLayout.addLayout(self.centralwidget_hlayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.phone_number_label.setText(_translate("Form", "Phone Number"))
        self.female_radiobtn.setText(_translate("Form", "Female"))
        self.checkBox.setText(_translate("Form", "Enable two factor authentication (2FA)"))
        self.login_question_label.setText(_translate("Form", "Already have an account? "))
        self.cpassword_label.setText(_translate("Form", "Confirm Password"))
        self.male_radiobtn.setText(_translate("Form", "Male"))
        self.sign_up_btn.setText(_translate("Form", "Sign Up"))
        self.password_label.setText(_translate("Form", "Password"))
        self.name_label.setText(_translate("Form", "Full Name"))
        self.city_label.setText(_translate("Form", "City"))
        self.gener_label.setText(_translate("Form", "Gender"))
        self.country_label.setText(_translate("Form", "Country"))
        self.email_label.setText(_translate("Form", "Email"))
        self.sign_up_label.setText(_translate("Form", "SIGN UP"))
        self.login_btn.setText(_translate("Form", "Login"))
import resources_rc
