# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'two_factor_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PIL.ImageQt import ImageQt 
from PyQt5.QtWidgets import QWidget

from signals import MySignal

class TwoFactorWidget(QWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.ui = Ui_Form()
        self.ui.setupUi(self)
        self.signal = MySignal()
        self.signal.signal_qr_code.connect(lambda img: self.display_qr_code(img))

    def display_qr_code(self, pil_image):
        self.ui.qr_label.setPixmap(QtGui.QPixmap.fromImage(ImageQt(pil_image)))


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 576)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.centralwidget_hlayout = QtWidgets.QHBoxLayout()
        self.centralwidget_hlayout.setSpacing(0)
        self.centralwidget_hlayout.setObjectName("centralwidget_hlayout")
        self.left_frame = QtWidgets.QFrame(Form)
        self.left_frame.setMinimumSize(QtCore.QSize(511, 0))
        self.left_frame.setAutoFillBackground(False)
        self.left_frame.setStyleSheet("background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgba(14, 201, 242, 107), stop: 1 rgba(34, 173, 204, 255));")
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.left_frame_vlayout = QtWidgets.QVBoxLayout()
        self.left_frame_vlayout.setObjectName("left_frame_vlayout")
        self.logo = QtWidgets.QLabel(self.left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMaximumSize(QtCore.QSize(290, 90))
        self.logo.setStyleSheet("background: none")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/images/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.left_frame_vlayout.addWidget(self.logo)
        self.ellipse = QtWidgets.QFrame(self.left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ellipse.sizePolicy().hasHeightForWidth())
        self.ellipse.setSizePolicy(sizePolicy)
        self.ellipse.setMinimumSize(QtCore.QSize(350, 350))
        self.ellipse.setMaximumSize(QtCore.QSize(350, 350))
        self.ellipse.setStyleSheet("border-radius: 175")
        self.ellipse.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ellipse.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ellipse.setObjectName("ellipse")
        self.ellipse_icon = QtWidgets.QLabel(self.ellipse)
        self.ellipse_icon.setGeometry(QtCore.QRect(70, 60, 201, 241))
        self.ellipse_icon.setStyleSheet("background: none\n"
"\n"
"")
        self.ellipse_icon.setText("")
        self.ellipse_icon.setPixmap(QtGui.QPixmap(":/images/phone.png"))
        self.ellipse_icon.setScaledContents(True)
        self.ellipse_icon.setObjectName("ellipse_icon")
        self.left_frame_vlayout.addWidget(self.ellipse, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.left_frame_vlayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.left_frame_vlayout)
        self.centralwidget_hlayout.addWidget(self.left_frame)
        self.right_frame = QtWidgets.QFrame(Form)
        self.right_frame.setMinimumSize(QtCore.QSize(511, 0))
        self.right_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.right_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grid_layout = QtWidgets.QGridLayout()
        self.grid_layout.setContentsMargins(20, 20, 40, 20)
        self.grid_layout.setHorizontalSpacing(12)
        self.grid_layout.setObjectName("grid_layout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_layout.addItem(spacerItem1, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.grid_layout.addItem(spacerItem2, 0, 0, 1, 1)
        self.title_label = QtWidgets.QLabel(self.right_frame)
        self.title_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color: \"#28B1D0\";\n"
"font-weight: bold;\n"
"margin: 10px 0 ")
        self.title_label.setTextFormat(QtCore.Qt.AutoText)
        self.title_label.setScaledContents(False)
        self.title_label.setWordWrap(False)
        self.title_label.setIndent(-3)
        self.title_label.setObjectName("title_label")
        self.grid_layout.addWidget(self.title_label, 1, 0, 1, 3)
        self.qr_label = QtWidgets.QLabel(self.right_frame)
        self.qr_label.setMaximumSize(QtCore.QSize(200, 200))
        self.qr_label.setText("")
        self.qr_label.setPixmap(QtGui.QPixmap(":/images/qrcode001.png"))
        self.qr_label.setScaledContents(True)
        self.qr_label.setObjectName("qr_label")
        self.grid_layout.addWidget(self.qr_label, 3, 0, 1, 2)
        self.description_label = QtWidgets.QLabel(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_label.sizePolicy().hasHeightForWidth())
        self.description_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.description_label.setFont(font)
        self.description_label.setStyleSheet("margin: 10px 0;")
        self.description_label.setObjectName("description_label")
        self.grid_layout.addWidget(self.description_label, 2, 0, 1, 5)
        self.continue_btn = QtWidgets.QPushButton(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.continue_btn.sizePolicy().hasHeightForWidth())
        self.continue_btn.setSizePolicy(sizePolicy)
        self.continue_btn.setMinimumSize(QtCore.QSize(150, 44))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.continue_btn.setFont(font)
        self.continue_btn.setStyleSheet("\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    background-color: \"#24AFCD\";\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;\n"
"}")
        self.continue_btn.setObjectName("continue_btn")
        self.grid_layout.addWidget(self.continue_btn, 4, 3, 1, 1)
        self.gridLayout_2.addLayout(self.grid_layout, 0, 0, 1, 1)
        self.centralwidget_hlayout.addWidget(self.right_frame)
        self.horizontalLayout.addLayout(self.centralwidget_hlayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title_label.setText(_translate("Form", "Two-factor authentication (2FA)"))
        self.description_label.setText(_translate("Form", "Scan the code bellow using Google Authenticator..."))
        self.continue_btn.setText(_translate("Form", "Continue"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
